{{ if .Values.clusterGroup.isHubCluster }}
---
apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: ldap-secret
  namespace: ldap-sync
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: ldap-secret
    template:
      type: Opaque
  dataFrom:
    - key: {{ .Values.ldapBindSecret.key }}
{{ end }}
